### ISSUE TITLE
Debug why art guide returns audio about the wrong painting

### ISSUE THREAD

**Issue by aguschin** [aguschin/art-guide#52]
If you try sending a picture from the reference database, the bot seem to find the wrong picture (although it finds something). Probably, we have some bug in matching the search result to the text description in the dataframe.

**Comment by mohammadsanaee** [comment]
I just checked the files related to this matter:
csv file has 191340 rows
embeddings has 191264
and the number of images in full folder are 191264

**Comment by aguschin** [comment]
Great finding @mohammadsanaee! Can we remove extra rows in csv file? We can do it in python process after we read + add an assertion to make sure the number of embeddings equals the number of rows in the dataframe.

**Comment by aguschin** [comment]
Fixed
